### ISSUE TITLE
Adding publications with .bib  - how to? 

### ISSUE THREAD

**Issue by sbrunswi** [RCODI/rcodi-blog#1]
**adding publications**

**What is the problem**
I tried to add a publication via netlify but I did not figure out how to add the .bib format? Can you share the documentation for that?
I also added the references.bib file to the repo - if that could be used to display references that would be good! 
** Request for advice**
@charrismatic Matt can you figure out how to do this?

**Comment by charrismatic** [comment]
I think you are looking for this project here

https://github.com/wowchemy/hugo-academic-cli

**Comment by sbrunswi** [comment]
Ok - trying this now.

**Comment by sbrunswi** [comment]
@charrismatic  I checked netlify and it has a lot of options
![Screen Shot 2021-02-16 at 10 39 27 AM](https://user-images.githubusercontent.com/12464227/108085521-6c7a3480-7043-11eb-8582-9cdf6726c33e.png)
I wonder how we add those to bibtex - still not clear to me. Maybe that is something Bryan can look into.

**Comment by charrismatic** [comment]
I think this is resolved now that the .bib file import is working
