### ISSUE TITLE
Slider Image Anchoring

### ISSUE THREAD

**Issue by ybvau** [RCODI/rcodi-blog#14]
@charrismatic  I can't figure out how to anchor slider images at the top -- would you be able to take a look and see if it is possible?

**Comment by charrismatic** [comment]
The style is set in a custom css file linked in the commit here 6181e4379423fe198e0ee29d97938c0e35ade344

Now that you've changed the images in the slide this looks a lot better.

**Comment by sbrunswi** [comment]
On my screen, it should only be the first slider image that is anchored at the top! The second one now does not show the back of the t-shirt anymore so it should be anchored center. the same for the last slider! @charrismatic @ybvau

**Comment by charrismatic** [comment]
There's no option to anchor individual slides. The only thing we can do is apply is globally to all slides through css

**Comment by sbrunswi** [comment]
ok - then we have to cut the images I guess :-(

**Comment by charrismatic** [comment]
It may be helpful to make sure that all the images are the same size and shape and that there is a safe zone around the edges where it may scale out of frame

**Comment by ybvau** [comment]
Re-scaled Maria img. Reopen if it does not meet expectations
