### ISSUE TITLE
"Get Involved"

### ISSUE THREAD

**Issue by ybvau** [RCODI/rcodi-blog#27]
The Get Involved section can be improved to highlight what the center is looking for in terms of partnership and potential team members. Create a page highlighting the specifics of what need to be done by:

1. Including on the page the open projects looking for help
2. The type of help these projects need

I was thinking this would be done in a job-board style. Opinions on how it comes along would be appreciated!

**Comment by ybvau** [comment]
Bump
The "Get Involved" page and "hook" are not inviting - we need to design a more inviting, central, and interesting way to entice motivated grad/undergrads from anywhere. 



Notes
--Note: a main attractor to RCODI could be the IronHacks program 
-- -- "If you're interested in this,

**Comment by sbrunswi** [comment]
Here some pages that are really upfront: http://hyoun.me/

**Comment by ybvau** [comment]
Updated with [7da82a8](https://github.com/RCODI/rcodi-blog/commit/7da82a8eb69d3b0707a6668c99154c8802968d06)
Still in progress

**Comment by twinblade02** [comment]
Recommend closure, as this has been addressed.
