### ISSUE TITLE
Adding team members 

### ISSUE THREAD

**Issue by sbrunswi** [RCODI/rcodi-blog#4]
Step ONE: Add fellows 
1) Create a second section in our people called "Fellows" = each needs to folder with a markdown in authors! 
2) List of fellows: 
     Satyam, Matt, Jia, Mai, Elizabeth, Bryan, Harshan, Iryna, Shatayu 
3) Copy the folder from sabine; Folder name: lower case
4) adjust the .md - you change the user group to Research Fellows, and ## for the twitter and linkedin. 
5) Add the sentence/statement about them under undernath ---
6) Add the avatar.jpg (rename the image from the original page as avatar.jpg) 

Step TWO: alumni

See above

**Comment by ybvau** [comment]
Almost done, I have to mirror author names w/in .md to match folder name. Then to alumni!

**Comment by charrismatic** [comment]
There were a few errors in the latest commit. I've fixed them and pushed it back to GitHub now. Make sure you have a look at the correct syntax before you update the next round.

https://github.com/RCODI/rcodi-blog/blob/master/content/authors/bryan-jacobs/_index.md

**Comment by ybvau** [comment]
Alumni done
