### ISSUE TITLE
[Forum post] Vineet introduction

### ISSUE THREAD

**Issue by ybvau** [RCODI/rcodi-blog#43]
We need to highlight Vineet on the RCODI blog. The purpose is to give a general introduction of him!

- [ ]  Write about what Vineet is currently researching
- [ ]  Highlight Vineet's aspirations and interests!

**Comment by vineet-mohanty** [comment]
Hello. This is Vineet. I will update my research interests today.

**Comment by vineet-mohanty** [comment]
Vineet is currently pursuing his doctoral research at Purdue. His research focus is at the intersection of Machine Learning and Big Data for Open-Source Software (OSS) supply chain. Using techniques from network science and graph analytics, he is analyzing the criticality of a software package in an OSS ecosystem. Vineet is a Mechanical Engineer by training with special interests in computational techniques and algorithm development for designing smart energy systems.
