### ISSUE TITLE
Move some members to "Alumni"

### ISSUE THREAD

**Issue by ybvau** [RCODI/rcodi-blog#50]
Three team members need to be moved to Alumni: Marlenn, Feny, and Mai. Make sure that their bio reflects their affiliation with the research center.

**Comment by sbrunswi** [comment]
Alumni: Marlen, Feny, and Mai
New members: Add Christopher (new grad student), and potentially also adding Santiago de Torres

**Comment by ybvau** [comment]
Members moved. TBD: Adding Christopher and Santiago

**Comment by ybvau** [comment]
@sbrunswi Close issue for now (to promote a cleaner ticketing operation) or add Christopher + Santiago?

**Comment by ybvau** [comment]
Primed for Christopher and Santiago [25e83db](https://github.com/RCODI/rcodi-blog/commit/25e83dbcd91f57385392627eb055e8fdd889f53e)
