### ISSUE TITLE
Pull our projects from posts

### ISSUE THREAD

**Issue by sbrunswi** [RCODI/rcodi-blog#6]
1) pull out projects from posts and move to projects: Note all posts that are NOT labelled as news are projects. it should be about 20 I think
2) Clean up the ironhacks project page first as this is the one we want to link to
3) Unpublish posts that are older than 1 or 2 years?

**Comment by ybvau** [comment]
bump -- I think this has been addressed but am not certain enough to close it

**Comment by twinblade02** [comment]
This has been addressed, recommend closure of issue.
