### ISSUE TITLE
publications - question

### ISSUE THREAD

**Issue by sbrunswi** [RCODI/rcodi-blog#7]
@charrismatic  
# The issue
Currently we have one publication section - in there we have all the content that is structured according to APA and standard grouping and it also contains working papers! I think we should move out "media" and "other products" which is basically  1) news we are we featured in the press and also linkt our github pages. 
# question - idea
Shouldn't all the in the media put into "news" or should we just create a new section called "in the news"?  For the github products we should have a separate page? let's discuss this.

**Comment by sbrunswi** [comment]
@charrismatic  can you answer thsi please!

**Comment by charrismatic** [comment]
I'm not exactly sure what the question here is:

> Currently we have one publication section - in there we have all the content that is structured according to APA and standard grouping and it also contains working papers! 

This is a feature of the theme we're using and is a defined custom archetype as part of the hugo module. The types of publications and filtering options are not defined by us when we build the site.

> I think we should move out "media" and "other products" which is basically 1) news we are we featured in the press and also linkt our github pages.

The publications are defined and then built from the `references.bib` file when the `academic-cli` is run.

The first thing is to identify anything that's not a publication and remove it from the publication master .bib file

> Shouldn't all the in the media put into "news" or should we just create a new section called "in the news"? For the github products we should have a separate page? let's discuss this.

Anything not a publication is either a "project" or a "post" type. Either of these accepts categories and tags which could be used to classify something as "news", "media", "github". 

If you want to have a page that filters posts of a specific category this is possible using the page builder elements.

Right now there is already a "Latest news" section on the front page which filters posts that have the category "news" and are flagged as "featured"

**Comment by ybvau** [comment]
stale
