### ISSUE TITLE
[Blog] Featuring IronHacks Fall 2022 Winners

### ISSUE THREAD

**Issue by jasminebui1225** [RCODI/rcodi-blog#74]
- A blog post on the winners: introduce the challenge, their background & thoughts about IronHacks Challenge.

**Comment by jasminebui1225** [comment]
Title: IronHacks Fall 2022 Challenge: 10 Winners Revelation! 
Tags: IronHacks, Data Science.

Another IronHacks Challenge has come to an end where we have successfully found our top 10 winners. We have held an award ceremony in mid February to celebrate the amazing hard work of these winners.

### About the Challenge
The Fall 2022 Challenge focused on Indiana’s Unemployment Rate and building prediction model for future weeks to inform decision-makers of the state about the impact of unemployment claims. 

During these 6 weeks, participants have got numerous opportunities to improve the submissions after getting immediate scores and feedback. As new data came in each week, IronHackers tuned their models and became adventurous with new techniques.
![image](https://user-images.githubusercontent.com/116818449/222864785-27616fe7-0631-4129-b287-6dc6706c343a.png)

### Our Winners

At the end, our 10 winners have revealed themselves for being persistent with incredible work on prediction models. As this challenge was divided into two groups, each has 5 winners.

Fifth Places: Dayoon Suh, Raghu Raman

Fourth Places: Juan Carlos Verduzco, Memoria Hu

Third Places: Kai Tang, Matthew Schnell

Second Places: Doug Crabill, Lionel D’silva.

And our First Places are: Kitthithat Krongchon, Link Lin. 

Congratulations to our winners! We are impressed by your amazing jobs in the challenge.
Moving forward, we are excited to host more data science learning challenges and hope to see more participants try their best solving these societal matters.

**Comment by jasminebui1225** [comment]
@sbrunswi @jialincheoh Hello, can you review this please? Thank you!

**Comment by twinblade02** [comment]
Closing issue, as the event as passed.
