### ISSUE TITLE
Sliders! 

### ISSUE THREAD

**Issue by sbrunswi** [RCODI/rcodi-blog#8]
#1: Currently the slides have images that are centered; on large screens that cuts off the face of people etc. 
#2: Solution proposed by Matt: anchor on top

**Comment by ybvau** [comment]
2) Slider issue #8: 
General format: 
No button
Slider 1: 
Picture Sabine
Sentence:  Shaping the future of digital innovation!
Text: orientation: 
Link to publications
         Slider 2: 
          *   Picture that represents "data science" or hacking - or the picture with Maria wearing our IronHack
Sentence: Hack data to solve global challenges! 
Text orientation: 
Link to IronHacks project on our page 
         Slide 3: 
Picture: Black and white representing a network graph
Sentence: Join a community of computational social scientists! 
Link to publication section

**Comment by ybvau** [comment]
Buttons removed
Slider 1 updated
Slider 2 updated
Slider 3 updated. Different image placed - If not I was not able to find the proper image without text.

Currently working on anchoring images

**Comment by sbrunswi** [comment]
@ybvau  here is the network image! I found it. https://rcodi.org/wp-content/uploads/2018/01/Starter-page-image.png
