### ISSUE TITLE
Blog post for OI Seminar Speech (May 15th)

### ISSUE THREAD

**Issue by jasminebui1225** [RCODI/rcodi-blog#86]
Title: New Open Innovation (OI) Speech by Dr. Sabine Brunswicker at Berkeley OI Seminar
Hashtags: #Research #OpenInnovation
Graphics:  [OI Seminar Talk.png](https://drive.google.com/file/d/1m46gEpf7T04jSA1kObpqo1tP-ImW1nC0/view?usp=share_link)

Content:
[Subheading] Spring 23 Berkeley Open Innovation Seminar on May 15th, 2023. 
The growing field of Open Innovation (OI) is welcoming more academic scholars today to present various research aspects in OI to a large audience of seasoned scholars, practitioners, aspiring young graduates and more at the 16th Open Innovation Seminar at Berkeley. 

With the topic of “Teaching Engineers about Open Innovation” , Dr. Brunswicker from Purdue University will be talking about experiential learning, cyclical framework and theoretical foundations in teaching engineering students and how they gain experience through solving real open innovation projects. Her presentation will start at 1 PM (EST) today along with other speeches from Prof Yao Sun (New Jersey Institute of Technology), Prof. Ann Majchrzak (University of Southern California), and Prof. Arvind Malhotra (University of North Carolina at Chapel Hill).

**Comment by jasminebui1225** [comment]
Title: New Open Innovation (OI) Speech by Dr. Sabine Brunswicker at Berkeley OI Seminar
Hashtags: #Research #OpenInnovation
Graphics:  [OI Seminar Talk 2.png](https://drive.google.com/file/d/1rJnQlOL6dsDD4Qx_bJmspAUCdl0ukLHB/view?usp=share_link)

Content for Blog:
[Subheading] Spring 23 Berkeley Open Innovation Seminar on May 15th, 2023. 

The growing field of Open Innovation (OI) is welcoming more academic scholars today to present various research aspects in OI to a large audience of seasoned scholars, practitioners, aspiring young graduates and more at the 16th Open Innovation Seminar at Berkeley. 

With the topic of “Teaching Engineers about Open Innovation” , Dr. Brunswicker from Purdue University will be talking about experiential learning, cyclical framework and theoretical foundations in teaching engineering students and how they gain experience through solving real open innovation projects. Excitingly, the presentation will start at 1 PM (EST) today along with other speeches from Prof Yao Sun (New Jersey Institute of Technology), Prof. Ann Majchrzak (University of Southern California), and Prof. Arvind Malhotra (University of North Carolina at Chapel Hill).

Regarding Dr. Brunswicker’s speech, we compose a list of case studies that utilizes open innovation concepts to solve complex, real-life problems in different fields. A complete, informative story for each case study is attached in separate sections, feel free to view it here: https://rcodi.org/oxfordhbcases. Let us know your opinions on these open innovation concepts!

**Comment by sbrunswi** [comment]
@jasminebui1225 can you add the twitter handles here that yuo want to use in twitter post (to tag). You need to reference the citation of the book chapter!

**Comment by sbrunswi** [comment]
cool social media post! just saw it.
