### ISSUE TITLE
Links in project pages outdated 

### ISSUE THREAD

**Issue by sbrunswi** [RCODI/rcodi-blog#9]
I reviewed some first project pages quickly. I noticed that the links are outdated.  e.g. https://www.slideshare.net/RCODI/purdue-unal-iron-hacks-2018-spring-award-ceremony for IronHacks.

I would like all of us to work on cleaning up ONE project together, and then working through the other ones.

Also, we should review the anchoring/ordering (time, priority, content, alphabetic, etc.). Not sure what is possible.

**Comment by ybvau** [comment]
Briefly revised/updated IH project page. @charrismatic  @sbrunswi  Would you be able to look over it to ensure it meets expectations? Only minor updates have been made.
