### ISSUE TITLE
New post regarding big press release on Cybersecurity

### ISSUE THREAD

**Issue by jasminebui1225** [RCODI/rcodi-blog#90]
**Cybersecurity article**
Article from Philip 
A post on RCODI, IronHacks, Twitter, LinkedIn
Stored in Zotero
Links Guac-alytics

**Comment by twinblade02** [comment]
## Draft of GUAC-ALYTICS and Press Release (@jasminebui1225; minor edits: @twinblade02 )

A growing force of study on software supply chains is occurring at Purdue University thanks to the collaboration between Dr. Sabine Brunswicker and Dr. Santiago Torres-Arias. While exploring for better understanding of these software structures, the GUAC-ALYTICS study aims to combat cybersecurity attacks introducing risks to a majority of companies that are utilizing open-source software (OSS). The rising challenges and holistic approaches when taking on this under-resourced topic are carefully documented through this Purdue Today article: link.

### About GUAC-ALYTICS
GUAC-ALYTICS focuses on increasing transparency and security of these OSS supply chains, which is originated from the GUAC project (Graph for Understanding Artifact Composition from Google and Kusari. With the use of theories and models of network science and machine learning, preliminary results have emphasized systems that can determine potential risks and suggest effective risk management methods. Not only that, future work of this program aims to discover different and better approaches to overcome the aforementioned problem. You can view the on-going study here: <link>

### A chance to contribute!
Dr. Brunswicker and Dr. Torres-Arias are looking for motivated students in doctoral, postdoctoral, and even undergraduate standing to join this effort!

**Comment by twinblade02** [comment]
Post is up; closing issue.
