### ISSUE TITLE
Email to individuals from outer departments 

### ISSUE THREAD

**Issue by twinblade02** [RCODI/rcodi-blog#91]
Following here is the content of the email we will be sending out to the people inside this emailing list: https://docs.google.com/spreadsheets/d/1J0Rv6zGvjVSVKjW5UPcf8LyxHq2_D3fRGw2udn4DkE8/edit#gid=0

"Hello everyone! 

RCODI is happy to announce a collaboration between Dr. Brunswicker and Dr. Santiago Torres; who are working towards building graph models to tackle software supply chain attacks!

This collaboration has appeared in the newsroom as a result of their efforts in tackling this problem, and taking a step forward in securing open-source software! The link to the article can be found here: <Link to RCODI post or Newsroom article>"

**Comment by jasminebui1225** [comment]
I'm currently working with Nick from PPI. And will follow up with Marketing team from CERIAS.
